export const COUNTRIES: Record<string, string> = {
  AD: 'Andorra',
  AR: 'Argentina',
  AT: 'Áustria (Österreich)',
  AU: 'Austrália (Australia)',
  BE: 'Bélgica (België)',
  BR: 'Brasil',
  BY: 'Bielorrússia (Беларусь)',
  CA: 'Canadá (Canada)',
  CH: 'Suíça (Schweiz)',
  CL: 'Chile',
  CO: 'Colômbia (Colombia)',
  CZ: 'Tchéquia (Česko)',
  DE: 'Alemanha (Deutschland)',
  DK: 'Dinamarca (Danmark)',
  EG: 'Egito (مصر)',
  ES: 'Espanha (España)',
  FI: 'Finlândia (Suomi)',
  FR: 'França (France)',
  GB: 'Reino Unido (United Kingdom)',
  GR: 'Grécia (Ελλάδα)',
  HR: 'Croácia (Hrvatska)',
  HU: 'Hungria (Magyarország)',
  IE: 'Irlanda (Ireland)',
  IL: 'Israel (ישראל)',
  IN: 'Índia (भारत)',
  IR: 'Irã (ایران)',
  IS: 'Islândia (Ísland)',
  IT: 'Itália (Italia)',
  JP: 'Japão (日本)',
  KR: 'Coreia do Sul (한국)',
  MX: 'México',
  NL: 'Países Baixos (Nederland)',
  NO: 'Noruega (Norge)',
  NZ: 'Nova Zelândia (New Zealand)',
  PL: 'Polônia (Polska)',
  PR: 'Porto Rico (Puerto Rico)',
  PT: 'Portugal',
  RO: 'Romênia (România)',
  RS: 'Sérvia (Srbija)',
  RU: 'Rússia (Россия)',
  SA: 'Arábia Saudita (المملكة العربية السعودية)',
  SE: 'Suécia (Sverige)',
  SI: 'Eslovênia (Slovenija)',
  SK: 'Eslováquia (Slovensko)',
  TH: 'Tailândia (ประเทศไทย)',
  TR: 'Turquia (Türkiye)',
  UA: 'Ucrânia (Україна)',
  US: 'Estados Unidos (United States)',
  UY: 'Uruguai (Uruguay)',
  VE: 'Venezuela',
  ZA: 'África do Sul (South Africa)',
  CN: 'China (中国)',
}

export function countryName(code: string | null | undefined, short = false): string {
  if (!code) return '—'
  const full = COUNTRIES[code.toUpperCase()] ?? code
  if (short) return full.replace(/\s*\(.*\)$/, '').trim()
  return full
}
