export const COUNTRIES: Record<string, string> = {
  // ocidentais — nome no idioma nativo
  AD: 'Andorra',
  AR: 'Argentina',
  AT: 'Österreich',
  AU: 'Australia',
  BE: 'België',
  BR: 'Brasil',
  BY: 'Беларусь (Bielorrússia)',
  CA: 'Canada',
  CH: 'Schweiz',
  CL: 'Chile',
  CO: 'Colombia',
  CZ: 'Česko',
  DE: 'Deutschland',
  DK: 'Danmark',
  ES: 'España',
  FI: 'Suomi',
  FR: 'France',
  GB: 'United Kingdom',
  GR: 'Ελλάδα (Grécia)',
  HR: 'Hrvatska',
  HU: 'Magyarország',
  IE: 'Ireland',
  IL: 'ישראל (Israel)',
  IS: 'Ísland',
  IT: 'Italia',
  MX: 'México',
  NL: 'Nederland',
  NO: 'Norge',
  NZ: 'New Zealand',
  PL: 'Polska',
  PR: 'Puerto Rico',
  PT: 'Portugal',
  RO: 'România',
  RS: 'Srbija',
  RU: 'Россия (Rússia)',
  SE: 'Sverige',
  SI: 'Slovenija',
  SK: 'Slovensko',
  TR: 'Türkiye',
  UA: 'Україна (Ucrânia)',
  US: 'United States',
  UY: 'Uruguay',
  VE: 'Venezuela',
  ZA: 'South Africa',

  // não-ocidentais — nativo (pt-BR)
  CN: '中国 (China)',
  JP: '日本 (Japão)',
  KR: '한국 (Coreia do Sul)',
  TH: 'ประเทศไทย (Tailândia)',
  IN: 'भारत (Índia)',
  SA: 'المملكة العربية السعودية (Arábia Saudita)',
  EG: 'مصر (Egito)',
  IR: 'ایران (Irã)',
}

export function countryName(code: string | null | undefined): string {
  if (!code) return '—'
  return COUNTRIES[code.toUpperCase()] ?? code
}
